version: '3.8'
services:
#  app:
  db:
    image: 'postgres:16.1'
    restart: always
    environment:
      POSTGRES_DB: 'users'
      POSTGRES_USER: 'pguser'
      POSTGRES_PASSWORD: 'pgpass'
      PGDATA: '/var/lib/postgresql/data/ms_pgdata'
    volumes:
      - './db/init.sql:/docker-entrypoint-initdb.d/init.sql'
      - './db/postgres-data:/var/lib/postgresql/data'
    ports:
      - '5433:5432'


